"""
STEP 5: Answer Generation
Input: Communities and user query
Output: Final answer generated by LLM
"""

from typing import List
from openai import OpenAI
from config import ANSWER_MAX_TOKENS, MAX_COMMUNITIES_FOR_ANSWER


class AnswerOutput:
    """Output của bước answer generation"""
    def __init__(self, answer: str, stats: dict):
        self.answer = answer
        self.stats = stats
    
    def print_summary(self):
        print("\n" + "=" * 80)
        print("STEP 5: ANSWER GENERATION - OUTPUT")
        print("=" * 80)
        print(f"❓ Query: {self.stats['query']}")
        print(f"👥 Số communities sử dụng: {self.stats['num_communities_used']}")
        print(f"📝 Độ dài context: {self.stats['context_length']} ký tự")
        print(f"🤖 Model: {self.stats['model']}")
        print(f"📊 Độ dài answer: {self.stats['answer_length']} ký tự")
        print("\n" + "=" * 80)
        print("FINAL ANSWER")
        print("=" * 80)
        print(self.answer)
        print("=" * 80)
    
    def save_to_file(self, output_dir: str = "pipeline_outputs"):
        """Lưu output ra file txt"""
        import os
        os.makedirs(output_dir, exist_ok=True)
        
        filepath = os.path.join(output_dir, "step5_answer_output.txt")
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("=" * 80 + "\n")
            f.write("STEP 5: ANSWER GENERATION - DETAILED OUTPUT\n")
            f.write("=" * 80 + "\n\n")
            
            # Stats
            f.write("📊 THỐNG KÊ:\n")
            f.write(f"   - Query: {self.stats['query']}\n")
            f.write(f"   - Số communities sử dụng: {self.stats['num_communities_used']}\n")
            f.write(f"   - Độ dài context: {self.stats['context_length']} ký tự\n")
            f.write(f"   - Model: {self.stats['model']}\n")
            f.write(f"   - Độ dài answer: {self.stats['answer_length']} ký tự\n\n")
            
            # Answer
            f.write("=" * 80 + "\n")
            f.write("📝 CÂU TRẢ LỜI CUỐI CÙNG:\n")
            f.write("=" * 80 + "\n\n")
            f.write(self.answer)
            f.write("\n\n")
        
        print(f"💾 Đã lưu output vào: {filepath}")
        return filepath


class AnswerGenerator:
    """Class để tạo câu trả lời từ communities"""
    
    SYSTEM_PROMPT = """Dựa trên các nhóm khái niệm và quan hệ, hãy trả lời câu hỏi một cách chi tiết bằng tiếng Việt.

Hướng dẫn:
- Sử dụng thông tin từ các nhóm kiến thức được cung cấp
- Trả lời trực tiếp và súc tích
- Nếu thông tin không đủ, hãy nói rõ
- Cấu trúc câu trả lời logic và dễ hiểu
"""
    
    def __init__(self, api_key: str):
        self.client = OpenAI(api_key=api_key)
    
    def _format_communities(self, communities: List[List[str]]) -> str:
        """Format communities thành text để đưa vào LLM"""
        comm_descriptions = []
        
        # Chỉ lấy số lượng communities giới hạn
        selected_communities = communities[:MAX_COMMUNITIES_FOR_ANSWER]
        
        for i, comm in enumerate(selected_communities):
            # Lấy tối đa 10 entities đầu tiên của mỗi community
            entities = ', '.join(comm[:10])
            if len(comm) > 10:
                entities += f" ... (+{len(comm) - 10} entities khác)"
            
            comm_descriptions.append(f"Nhóm {i+1}: {entities}")
        
        return "\n".join(comm_descriptions)
    
    def generate(self, communities: List[List[str]], query: str) -> AnswerOutput:
        """
        Tạo câu trả lời dựa trên communities và query
        
        Args:
            communities: List of communities (mỗi community là list of entity names)
            query: User's question
            
        Returns:
            AnswerOutput: Object chứa answer và stats
        """
        # Format communities thành context
        context = self._format_communities(communities)
        
        # Tạo prompt
        user_prompt = f"""
Câu hỏi: {query}

Các nhóm kiến thức chính:
{context}
"""
        
        # Gọi LLM
        response = self.client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": self.SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt}
            ],
            max_tokens=ANSWER_MAX_TOKENS
        )
        
        answer = response.choices[0].message.content
        
        # Tính toán stats
        stats = {
            'query': query,
            'num_communities_used': min(len(communities), MAX_COMMUNITIES_FOR_ANSWER),
            'context_length': len(context),
            'model': 'gpt-4o',
            'answer_length': len(answer)
        }
        
        return AnswerOutput(answer, stats)